=head1 NAME

equivs-build - make a debian package to register local software

=head1 SYNOPSIS

B<equivs-build [--full|-f] controlfile>

=head1 DESCRIPTION

This is a package, that creates Debian packages that can be 
used to inform dpkg about localy installed packages and their 
dependancies. Also empty packages that just require other packages
can be created with equivs. These can be used as "profile" packages 
that just mark otherones for installation.

Please note that this is a crude hack and if thoughtlessly used
might possibly do damage to your packaging system. And please
note as well that using it is not the recommended way of dealing
with broken dependencies. Better file a bug report instead.

The control file has a structure like the control files in "real"
Debian packages, but it doesn't have to define all keys, as default 
ones will be used, if you omit one.

There are four additional fields that can be used:

=over 4

=item Changelog: 

File to be used as the changelog

=item Version: 

If you don't use a local changelog, equivs will create a
dummy one. As the version of the package is defined in the
changelog, equivs will asume the version 1.0. With this
field, you can set an explicit version.

=item Readme: 

A file to be used as the README.Debian file. You can use the
strings §packagename§ and §depends§ to insert the package
name and the dependency information used.

=item Copyright: 

The copyright file to by used. If ommited, the GPL 2 
will be used.

=item Extra-Files:

A comma-seperated list of files to copy to the 
/usr/doc/packagename directory.

=back

See /usr/doc/equivs/README.Debian for more information.

=head1 OPTIONS

=over 4

=item --full | -f

Do a complete build. debuild will be called, that is a 
full package will be build and signed, suitable for a upload 
to the Debian servers. 

The ID used to signed is taken from, in that order, the User from 
the last entry of a supplied changelog, the Maintainer: field in the 
equivs control file, the local username.

=back

=head1 DISTRIBUTION

Distribution is subject to the GNU public licence version 2.

=head1 AUTHOR

Martin Bialasinski <martinb@debian.org>

=head1 SEE ALSO

equivs-control(1), /usr/doc/equivs/README.Debian
